apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-config
data:
  postgres_db: appdb
  postgres_host: postgres-service
  postgres_port: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-secrets
type: Opaque  
data:
  postgres_user: cG9zdGdyZXM=
  postgres_password: cG9zdGdyZXM=


