---
apiVersion: v1
kind: Service
metadata:
  name: k8s-api-service
  labels:
    app: k8s-api
spec:
  type: NodePort
  selector:
    app: k8s-api
  ports:
    - protocol: TCP
      name: k8s-api-port-mapping
      port: 8080
      targetPort: 8080
      nodePort: 30090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-api
  labels:
    app: k8s-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-api
  template:
    metadata:
      labels:
        app: k8s-api
    spec:
      containers:
      - image: sbouhaddi/k8s-api
        name: k8s-api
        ports: 
          - containerPort: 8080
        env: 
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
          - name: DB_HOST
            valueFrom :
              configMapKeyRef:
                name: k8s-config
                key: postgres_host
          - name: DB_PORT
            valueFrom :
              configMapKeyRef:
                name: k8s-config
                key: postgres_port
          - name: DB_DATABSE
            valueFrom:
              configMapKeyRef:
                name: k8s-config
                key: postgres_db
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: k8s-secrets
                key: postgres_user
          - name: DB_PASSWWORD
            valueFrom:
              secretKeyRef:
                name: k8s-secrets
                key: postgres_password